# Generated by Django 2.2.6 on 2020-03-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20200324_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='product',
            new_name='booking_id',
        ),
    ]
